### ISSUE TITLE
optional <ORDER_DATE> causes an error in validation when not present

### ISSUE THREAD

**Issue by TanvedraX** [warappa/OpenTransSharp#10]
Sample XML:
 
<CUSTOMER_ORDER_REFERENCE>
		<ORDER_ID>a</ORDER_ID>
</CUSTOMER_ORDER_REFERENCE>

deserializes fine as it should but document.Validate(serializer) reports an error:

"/ORDER/ORDER_HEADER[1]/ORDER_INFO[1]/CUSTOMER_ORDER_REFERENCE[1]/ORDER_DATE[1]": [
"If the 'nillable' attribute is false in the schema, the 'xsi:nil' attribute must not be present in the instance.",
"The 'http://www.opentrans.org/XMLSchema/2.1:ORDER_DATE' element is invalid - The value '' is invalid according to its datatype 'http://www.bmecat.org/bmecat/2005:dtDATETIME' - The Pattern constraint failed."]

**Comment by warappa** [comment]
Hi @ftanvedra ,
this is indeed a bug in the serialization mapping. I will try to push out a fix shortly.
Thank you for your bug report!

<details>
<summary>Technical detail</summary>

`public bool DateSpecified => Date.HasValue;` is missing at `CustomerOrderReference.Date`.

</details>

**Comment by warappa** [comment]
Should be fixed by 7908fb8d233f39b15d2ef46f541b988082e87824.

Released with version 1.0.1.
