### ISSUE TITLE
wrong BMEcatDocument namespace?

### ISSUE THREAD

**Issue by Jazzman1976** [warappa/OpenTransSharp#11]
Hello @warappa ,

In your code I can see you use:
```
[XmlRoot("BMECAT", Namespace = "http://www.bmecat.org/bmecat/2005")]
public class BMEcatDocument
```

This does not work with my BMECAT, because it uses:
`<BMECAT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2005" xmlns="http://www.bmecat.org/bmecat/2005fd">`

You see, it has the ending 2005fd in the namespace.

When I change it in the XML to 2005 at the end it is working.

Can I get this working somehow by using any parameter or option?

My code looks like this:

```
        public static BMEcatDocument GetBMEcatDocument(
            this Stream stream, 
            out string errorMessage, 
            BMEcatXmlSerializerOptions options = null)
            
        {
            // init return values
            BMEcatDocument theDoc = null;
            errorMessage = null;

            // get serializer factory
            BMEcatXmlSerializerFactory fac = new BMEcatXmlSerializerFactory(
                options ?? new BMEcatXmlSerializerOptions 
                {
                    // add default options if needed
                });

            // deserialize and validate the document
            try
            {
                XmlSerializer serializer = fac.Create<BMEcatDocument>();
                theDoc = serializer.Deserialize<BMEcatDocument>(stream);
                theDoc.EnsureValid(serializer);
            }
            catch (Exception exc)
            {
                errorMessage = exc.Message;
            }

            return theDoc;
        }
    }
```

**Comment by Jazzman1976** [comment]
Not sure if it is a bug. All info from the bme website and all examples show "2005fe" is used as namespace... 🤔

**Comment by Jazzman1976** [comment]
@pedropauloreis Do you work with the BMEcat import, too? What was your experience?

**Comment by warappa** [comment]
Hi @Jazzman1976 ,
thank you for using this libary 😊

The `fd` in `2005fd` means "**Final Draft**", so it is the _predecessor_ to the 2005 version (the German Wikipedia article uses the "2005fd" version in its example which is unfortunate).
There were some (minor?) changes from final draft to 2005 which may or may not be a problem for your use-case. You can read about the changes in the file `src/Content/en/bmecat_2005_en.pdf`, section "History of changes Version 2005". If you use some of the renamed elements you may could try to use **XSLT** to do a "fix-up".

On the technical side, as far as I know the .NET `XmlSerializer` does not allow for multiple namespaces to be applied to the XML-elements/attributes. So as it stands, OpenTransSharp can only support 1 - exactly 1 - version of BMEcat, although this is also very unfortunate to me.
But I would like to be corrected on this one if it's possible 🙂

**Comment by Jazzman1976** [comment]
@warappa 
thank you for your reply.

I'll try to change or ignore the namespace somehow using the XmlTextReader or any other way in the code.

I think you could just add another BMECAT object, maybe BMECAT_FD or something like this.
This could use the other namespace.

But when I understand correctly, this also has some minor differences to the final BMECAT 2005 release version.

In addition, I ask the supplier of the XML I this could be changed in the exported BMECAT XML file.

I'll share my results here...

**Comment by Jazzman1976** [comment]
@warappa 

The service provider who creates the XML argues with the namespace declaration in the offical XSD file, which can be downloaded here: https://www.bme.de/services/bmecat/downloads_BMEcat in the "BMECAT 2005" Tab.
It is correct, it also uses the "fd" namespace.

They say, it's also the namespace for the released BMECAT 2005 version, not only the final draft.

I can't find any information about what is correct and how to use it. I start a conversation with BME to clarify this.

**Comment by Jazzman1976** [comment]
According to the documentation of BMEcat 2005, the namespace in the XSD file is also 

```xmlns="http://www.bmecat.org/bmecat/2005fd"```

This seems to be correct, even if the BMEcat 2005 is NOT the final draft version. Maybe the namespace was not changed after the Final Draft was going to the release version.
BME told me this was fixed with BME2005.1 and later versions.

Wrote an E-Mail to BME and asked for the correct namespace in 2005 but they did not response, jet.

**Comment by warappa** [comment]
@Jazzman1976 I just digged around - here is what I found.

### BMEcat Website
Indeed, *as of now* the official 2005 download has the namespace with `fd` at the end.

### GitHub
If you search around for other - even really old - openTRANS libraries on GitHub, you find that many (all?) use a BMEcat namespace with has *no* `fd` suffix.
This is strange... which brings me to...

### openTRANS Website
If you go to the official *openTRANS* page and download the technical documentation (https://www.digital.iao.fraunhofer.de/de/publikationen/OpenTRANS21.html), then the included `bmecat_2005.xsd` has the BMEcat namespace _without_ the `fd` suffix.

### What To Do?
So we're in an odd place:
* BMEcat website download data seems to say  `2005fd` is the right one,
* openTrans website download data implictly says for BMEcat `2005` is the right one

As this is a library has an openTRANS focus I'm in favor of the "openTrans-way" of using just `2005` (which also seems more consistent with the actual history).

### BME Inquiries
Still, I'm interested in the response of your inquiry to BME to give an answer about what the official 2005 final xml namespace officially is (and also, if it is "2005fd" I would like to know how they expect consumers to differentiate between 2005 fd and 2005 final).

**Comment by warappa** [comment]
@Jazzman1976 Did you get a response from BME yet?

**Comment by warappa** [comment]
Closed due to inactivity
