### ISSUE TITLE
BMEcat Header Catalog Language is not multiple

### ISSUE THREAD

**Issue by Jazzman1976** [warappa/OpenTransSharp#12]
According to the spec https://a.storyblok.com/f/104752/x/bef34fe816/bmecat_2005_en.pdf it should be a multiple field.

I have an BMEcat XML that uses multiple languages and it does not work. It just takes the first language in the XML.

**Comment by warappa** [comment]
You're right @Jazzman1976 !

I will fix this in the next release.
