### ISSUE TITLE
ORDER Document type EMAIL differences

### ISSUE THREAD

**Issue by Benjamin23** [warappa/OpenTransSharp#14]
Hello @warappa ,

I've noticed 2 differences between handling email information in the library and the OpenTrans specification. 

The differences are in the ORDER Document Type and its ADDRESS information. 

According to the documentation, the ADDRESS -> CONTACT_DETAILS -> EMAILS field can be a list of email addresses. 
Int he source code, in the _\src\OpenTransSharp\Types\OpenTransContactDetails.cs_  the property is defined like this: 

```
        /// <summary>
        /// (optional) E-mail addresses<br/>
        /// <br/>
        /// List of e-mail addresses.<br/>
        /// <br/>
        /// XML-namespace: BMECAT
        /// </summary>
        [BMEXmlElement("EMAILS")]
        public global::BMEcatSharp.Email? Email { get; set; }
```

The comment states it is a list of emails, but the property is just one email. 

The 2nd difference is in the EMAIL field on the ADDRESS. From the documentation and examining the official XSD files, we see that the definition is the same as the EMAILS on the CONTACT_DETAILS, but in the code, we can only add a single email address. 

Would you be willing to consider changing the field logic according to the docs to the library? I could help with a PR with the changes if you agree with the field logic update and would be willing to accept them.

**Comment by warappa** [comment]
Thank you for your bug report. I'm currently looking into this.
