### ISSUE TITLE
Email fields XML serialization

### ISSUE THREAD

**Issue by Benjamin23** [warappa/OpenTransSharp#17]
First I would like to thank you for accepting my bug report #14 . 

I've installed the new package and updated my code, however, I've noticed that one of my tests is now failing.

When populating the email field, the objects are populated correctly, however, the final serialized XML doesn't contain the value unless we access it first. On first look, it looks like something with the Lazy evaluation. 

Here's a short snippet. In case I un-comment the _var x = ..._ line, the code works fine and the _Does.Contain_ assertion is successful. But in case we don't evaluate the emails and just call serialize, the final XML doesn't contain that information. 

``` 
// Here the address has email set to "ben@example.com"
var otAddress = new OpenTransSharp.Address
        {
           ...
            Emails = addressInformation.ContactInfo.Emails != null ? addressInformation.ContactInfo.Emails.Select(s => new Email
            {
                EmailAddress = s
            }).ToList() : null,
            ...
        };


 // var x = otAddress.Emails.First().EmailAddress;

 var options = new OpenTransXmlSerializerOptions();
 var serializerFactory = new OpenTransXmlSerializerFactory(options);

 var serializer = serializerFactory.Create<OpenTransSharp.Address>();

 string serializedContent = serializer.Serialize(otAddress);

 Assert.Multiple(() =>
 {
     Assert.That(serializedContent, Is.Not.Null);
     Assert.That(serializedContent, Does.Contain("ben@example.com"));
 });
```

**Comment by warappa** [comment]
Welp, I was weary about a case like that but thought my tests handle all the cases. 😬

To not repeat this issue again, I created a branch and PR. Please have a look at #18 and verify that I didn't miss something.

**Comment by Benjamin23** [comment]
Thanks @warappa for the quick reply. The tests look like the ones that I had, so they prove that everything is working correctly now. About the code, I would remove the Lazy logic, personally, I'm not a fan of hacks with `var _ = ...`  😄 But since everything is working correctly, who am I to complain 😄 

In any case, thank you once again for the quick reply.
